# Generated by Django 4.2.5 on 2023-10-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsModel',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter field documentation', max_length=20, unique=True)),
                ('timestamp', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='post_pictures/')),
                ('text', models.CharField(max_length=4000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPostActionsModel',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.actionsmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostTagsModel',
            fields=[
                ('post_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postmodel')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tagsmodel')),
            ],
        ),
    ]
