# Generated by Django 4.2.5 on 2023-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posttagsmodel',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posttagsmodel',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='userpostactionsmodel',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='userpostactionsmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='post_pictures/'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(help_text='Enter post tittle', max_length=100, unique=True),
        ),
    ]
