# Generated by Django 4.2.5 on 2023-10-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('username', models.CharField(help_text='Enter field documentation', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('hashed_password', models.CharField(max_length=150)),
                ('profile_picture', models.ImageField(upload_to='user_profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.usermodel')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='user.usermodel')),
            ],
        ),
    ]
