# Generated by Django 4.2.5 on 2023-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(help_text='Enter name', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='user_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(help_text='Enter username (Unique)', max_length=20, unique=True),
        ),
    ]
